{
 "title": "App Billing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage cost",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"app_api\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) / 10000",
     "legendFormat": "Cost of {{container_label_com_docker_swarm_service_name}} CPU"
    }
   ]
  },
  {
   "title": "Memory usage cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"app_api\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) + sum(container_memory_cache{container_label_com_docker_swarm_service_name=~\"app_api\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name)) / 100000000000",
     "legendFormat": "Cost of {{container_label_com_docker_swarm_service_name}} memory"
    }
   ]
  },
  {
   "title": "Network traffic cost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"app_api\"}[$interval])) by (container_label_com_docker_swarm_service_name) + sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"app_api\"}[$interval])) by (container_label_com_docker_swarm_service_name)) / 100000",
     "legendFormat": "Cost of {{container_label_com_docker_swarm_service_name}} traffic"
    }
   ]
  },
  {
   "title": "IOPS cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container_label_com_docker_swarm_service_name=~\"app_api\"}[$interval])) by (container_label_com_docker_swarm_service_name) +\nsum(rate(container_fs_writes_total{container_label_com_docker_swarm_service_name=~\"app_api\"}[$interval])) by (container_label_com_docker_swarm_service_name) / 10000",
     "legendFormat": "Cost of {{container_label_com_docker_swarm_service_name}} IOPS"
    }
   ]
  }
 ]
}